testAnalyseur: testAnalyseur.c graphe.c
	gcc -Wall -g -std=c99 testAnalyseur.c graphe.c -o testAnalyseur

exercice2:
	gcc -Wall -g -std=c99 monAnalyseur.c graphe.c -o monAnalyseur

visu:
	gcc -Wall -g -std=c99 visu.c graphe.c -o visu
