plusCourteDistance: plusCourteDistance.c graphe.c
	gcc -Wall -g -std=c99 plusCourteDistance.c graphe.c -o plusCourteDistance

plusCourtCheminAlea: plusCourtCheminAlea.c graphe.c
	gcc -Wall -g -std=c99 graphe.c plusCourtCheminAlea.c -o plusCourtCheminAlea
